from .base_interface import BaseInterface

PlinkoInterface = BaseInterface("Plinko")
RouletteInterface = BaseInterface("Roulette")
RockPaperScissorsInterface = BaseInterface("RPS")
ChestsInterface = BaseInterface("Chests")
LotteryInterface = BaseInterface("Lottery")
NewRpsInterface = BaseInterface("New_RPS")
NewChestsInterface = BaseInterface("New_Chests")
ChestsV3Interface = BaseInterface("ChestsV3")
VaultInterface = BaseInterface("Vault")
PredictionInterface = BaseInterface("Prediction")
PythInterface = BaseInterface("Pyth_Oracle")
FinalPredictionInterface = BaseInterface("Prediction_final")
PredictionClassicInterface = BaseInterface("Prediction_classic")
PredictionFixInterface = BaseInterface("Prediction_fix")